---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'Asynchronous and Parallel execution of the play'

  # Target: where our play will run and options it will run with
  hosts: all

  #variable: variables that will apply to the play, on all target systems
  vars:
    jobids: []

  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Task1
       command: /bin/sleep 5
       when: ansible_hostname == 'ansnode1'
       async: 10
       poll: 0
       register: result1
     - name: Task2
       command: /bin/sleep 5
       when: ansible_hostname == 'ansnode2'
       async: 10
       poll: 0
       register: result2
     - name: Task3
       command: /bin/sleep 30
       when: ansible_hostname == 'ansnode3'
       async: 10
       poll: 0
       register: result3
     - name: Task4
       command: /bin/sleep 5
       when: ansible_hostname == 'ansnode4'
       async: 10
       poll: 0
       register: result4
     - name: Capture Job IDs
       set_fact:
         jobids: >
                 {% if item.ansible_job_id is defined -%}
                    {{ jobids + [item.ansible_job_id] }}
                 {% else -%}
                    {{ jobids }}
                 {% endif %}
       with_items: "{{ [ result1, result2, result3, result4 ] }}"
     - name: Show Job IDs
       debug:
         var: jobids
     - name: 'Wait for Job IDs'
       async_status:
         jid: "{{ item }}"
       with_items: "{{ jobids }}"
       register: jobs_result
       until: jobs_result.finished
       retries: 30
# Three dots indicate the end of a YAML document
...
